### ISSUE TITLE
Run in a docker

### ISSUE THREAD

**Issue by LiorA1** [dexplo/dataframe_image#24]
Hi, when I trying to run the package inside a docker container I get:
```
>>> import dataframe_image as dfi
>>> dfi.export(df, 'dframe.png')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/dataframe_image/_pandas_accessor.py", line 24, in export
    return _export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
  File "/usr/local/lib/python3.8/site-packages/dataframe_image/_pandas_accessor.py", line 32, in _export
    converter = Screenshot(max_rows=max_rows, max_cols=max_cols, chrome_path=chrome_path,
  File "/usr/local/lib/python3.8/site-packages/dataframe_image/_screenshot.py", line 76, in __init__
    self.chrome_path = get_chrome_path(chrome_path)
  File "/usr/local/lib/python3.8/site-packages/dataframe_image/_screenshot.py", line 52, in get_chrome_path
    raise OSError("Chrome executable not able to be found on your machine")
OSError: Chrome executable not able to be found on your machine
```

Tried to look it up but find only some comments about "pip install chromium-chromedriver", but it seems that it cant be found..

Any help will be welcomed !

**Comment by tdpetrou** [comment]
You have to have some type of chrome executable available. And if it's not in a default location then I think there is a parameter that you can use to set the precise location of where the chrome executable is.

**Comment by GitHunter0** [comment]
Hey @tdpetrou , what Latex or Chrome method of installation do you recommend via docker? 
This hint would be very helpful. 
Thank you
