### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by LuizEduardo-service** [dexplo/dataframe_image#32]
Não consigo mais exportar o dataframe para uma imagem depois que compilei meu codigo em .exe com o pyinstaller
Apresenta o seguinte erro.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "automacao_dash.py", line 352, in atualiza_image
  File "automacao_dash.py", line 341, in selecao_dash_image
  File "automacao_dash.py", line 363, in cria_image_png
  File "dataframe_image\_pandas_accessor.py", line 24, in export
  File "dataframe_image\_pandas_accessor.py", line 32, in _export
  File "dataframe_image\_screenshot.py", line 77, in __init__
  File "dataframe_image\_screenshot.py", line 84, in get_css
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*****\\AppData\\Local\\Temp\\_MEI221163\\dataframe_image\\static\\style.css'

**Comment by redpower5x5** [comment]
this worked for me:
I created in **dist** folder **dataframe_image** and copied there **static** folder from package folder of **dataframe_image** located in **Lib** in my python venv folder
